### ISSUE TITLE
`favoriate_list` seems to use only two mutator types in havoc stage ?

### ISSUE THREAD

**Issue by ricardo-kcc** [puppet-meteor/EMS#1]
I found it seems to only use  `favoriate_list`  in the two mutator types of havoc stage , the other mutator types only record the location ?
https://github.com/puppet-meteor/EMS/blob/7990c322c51584c864e0da1d1be1b6a559c8786a/afl-fuzz.c#L13264
https://github.com/puppet-meteor/EMS/blob/7990c322c51584c864e0da1d1be1b6a559c8786a/afl-fuzz.c#L18682

**Comment by puppet-meteor** [comment]
Yep, we mainly use `favoriate_list` in our two customized mutators.

**Comment by ricardo-kcc** [comment]
it should change the biti value if the other mutators also use  `favoriate_list` ?

**Comment by puppet-meteor** [comment]
Of course, other mutators can utilize `favoriate_list`. I'm not sure of the meaning of the biti value. If I would like to implement the above function, I will utilize `favoriate_list` to locate the byte to be mutated, and then employ mutators. 
In our paper, we would like to measure the contribution of the algorithm. So we mainly add several customized data-driven mutators in MOPT. 
Since our code is open sourced, you can adjust the code on demand.

**Comment by ricardo-kcc** [comment]
ok, Thanks!
